[package]
name = "ffi-cbindgen-test"
version = "0.1.0"
authors = ["Alastair Daivis <alaroldai@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate_type = ["rlib", "staticlib"]
